services:
  consultant:
    container_name: consultant
    image: yuanyuexiang/consultant:v1
    restart: always
    ports:
      - "8000"
    environment:
      - APP_ENV=development
      - DEBUG=true
    #depends_on:
      #- postgres
      #- milvus
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consultant.rule=Host(`atlas.asksquirrel.ai`) && PathPrefix(`/consultant`)" # 替换为你的域名
      - "traefik.http.routers.consultant.entrypoints=websecure"
      - "traefik.http.routers.consultant.service=consultant"
      - "traefik.http.routers.consultant.tls=true"
      - "traefik.http.routers.consultant.tls.certresolver=cloudflare"
      - "traefik.http.services.consultant.loadbalancer.server.port=8000"

networks:
  matrix-network:
    external: true
