services:
  consultant:
    container_name: consultant
    image: yuanyuexiang/consultant:v1
    restart: always
    ports:
      - "3000"
    volumes:
      - ./consultant:/app/runtime
    environment:
      - APP_ENV=development
      - DEBUG=true
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consultant-web.rule=Host(`web.10.140.208.14.nip.io`) && PathPrefix(`/consultant`)" # 替换为你的域名
      - "traefik.http.routers.consultant-web.entrypoints=web"
      - "traefik.http.routers.consultant-web.service=consultant"
      - "traefik.http.routers.consultant-admin.rule=Host(`admin.10.140.208.14.nip.io`) && PathPrefix(`/consultant`)" # 替换为你的域名
      - "traefik.http.routers.consultant-admin.entrypoints=web"
      - "traefik.http.routers.consultant-admin.service=consultant"
      - "traefik.http.services.consultant.loadbalancer.server.port=3000"

networks:
  matrix-network:
    external: true
